name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [master, main]
    paths: ['docs/**', '.github/workflows/docs.yml']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build documentation site
        run: |
          # Create site structure
          mkdir -p _site
          
          # Copy documentation files
          cp -r docs/* _site/
          
          # Create dynamic index.html based on available files
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Nehal Ecky - Development Documentation</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 2rem;
                      color: #333;
                  }
                  h1, h2 { color: #2c3e50; }
                  .doc-links { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem; margin: 2rem 0; }
                  .doc-card { 
                      border: 1px solid #ddd; 
                      border-radius: 8px; 
                      padding: 1.5rem; 
                      text-decoration: none; 
                      color: inherit;
                      transition: transform 0.2s, box-shadow 0.2s;
                  }
                  .doc-card:hover { 
                      transform: translateY(-2px); 
                      box-shadow: 0 4px 12px rgba(0,0,0,0.1); 
                  }
                  .doc-card h3 { margin-top: 0; color: #3498db; }
                  .doc-list { list-style: none; padding: 0; }
                  .doc-list li { margin: 1rem 0; }
                  .doc-list a { display: block; padding: 1rem; border: 1px solid #ddd; border-radius: 8px; text-decoration: none; color: inherit; transition: transform 0.2s, box-shadow 0.2s; }
                  .doc-list a:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
                  .meta { color: #666; font-size: 0.9em; }
                  footer { margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #eee; text-align: center; color: #666; }
              </style>
          </head>
          <body>
              <header>
                  <h1>🔧 Development Documentation</h1>
                  <p>My development practices, system architecture, and workflow documentation.</p>
              </header>
              
              <main>
                  <section>
                      <h2>📚 Available Documentation</h2>
                      <ul class="doc-list">
          EOF
          
          # Add links for each markdown file found
          for md_file in _site/*.md; do
              if [ -f "$md_file" ]; then
                  base_name=$(basename "$md_file" .md)
                  html_file="${base_name}.html"
                  
                  # Extract title from first line of markdown (remove # prefix)
                  title=$(head -n1 "$md_file" | sed 's/^# //')
                  
                  # Extract description from first paragraph (skip empty lines and title)
                  description=$(sed -n '/^$/,$p' "$md_file" | sed '/^$/d' | head -n3 | tr '\n' ' ' | cut -c1-150)
                  
                  echo "                          <li><a href=\"$html_file\"><strong>$title</strong><br><small>$description...</small></a></li>" >> _site/index.html
              fi
          done
          
          cat >> _site/index.html << 'EOF'
                      </ul>
                  </section>
                  
                  <section>
                      <h2>🎯 Quick Links</h2>
                      <ul>
                          <li><a href="https://github.com/nehalecky/dotfiles">📁 Dotfiles Repository</a></li>
                          <li><a href="https://github.com/nehalecky/dotfiles/actions">⚙️ GitHub Actions</a></li>
                      </ul>
                  </section>
              </main>
              
              <footer>
                  <p class="meta">
                      Last updated: $(date +"%B %Y") • 
                      <a href="https://github.com/nehalecky/dotfiles">Source</a> • 
                      Generated with ❤️ and automation
                  </p>
              </footer>
          </body>
          </html>
          EOF
          
          # Install and use a proper markdown converter
          # Use Python's markdown library for better conversion
          pip install markdown
          
          # Convert markdown files to HTML using Python
          for md_file in _site/*.md; do
              if [ -f "$md_file" ]; then
                  base_name=$(basename "$md_file" .md)
                  html_file="_site/${base_name}.html"
                  title=$(head -n1 "$md_file" | sed 's/^# //')
                  
                  # Create HTML with proper styling
                  cat > "$html_file" << HTML_HEADER
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>$title - Development Documentation</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 2rem;
                      color: #333;
                  }
                  h1, h2, h3, h4, h5, h6 { color: #2c3e50; margin-top: 2rem; }
                  h1 { border-bottom: 2px solid #3498db; padding-bottom: 0.5rem; }
                  h2 { border-bottom: 1px solid #ecf0f1; padding-bottom: 0.3rem; }
                  code { 
                      background: #f8f9fa; 
                      padding: 0.2em 0.4em; 
                      border-radius: 3px; 
                      font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
                      font-size: 0.9em;
                  }
                  pre { 
                      background: #f8f9fa; 
                      padding: 1rem; 
                      border-radius: 8px; 
                      overflow-x: auto;
                      border: 1px solid #e9ecef;
                  }
                  pre code {
                      background: none;
                      padding: 0;
                  }
                  table { 
                      border-collapse: collapse; 
                      width: 100%; 
                      margin: 1rem 0;
                      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                  }
                  th, td { 
                      border: 1px solid #ddd; 
                      padding: 0.75rem; 
                      text-align: left; 
                  }
                  th { 
                      background: #3498db; 
                      color: white;
                      font-weight: 600;
                  }
                  tr:nth-child(even) { background: #f8f9fa; }
                  a { color: #3498db; text-decoration: none; }
                  a:hover { text-decoration: underline; }
                  .nav { 
                      margin-bottom: 2rem; 
                      padding: 1rem; 
                      background: #f8f9fa;
                      border-radius: 8px;
                      border-left: 4px solid #3498db;
                  }
                  ul, ol { padding-left: 2rem; }
                  li { margin: 0.5rem 0; }
                  blockquote {
                      border-left: 4px solid #3498db;
                      background: #f8f9fa;
                      margin: 1rem 0;
                      padding: 1rem 1rem 1rem 2rem;
                      border-radius: 0 8px 8px 0;
                  }
              </style>
          </head>
          <body>
              <nav class="nav">
                  <a href="index.html">← Back to Documentation Index</a>
              </nav>
              <div class="content">
          HTML_HEADER
                  
                  # Convert markdown to HTML using Python
                  python3 -c "
          import markdown
          import sys
          
          with open('$md_file', 'r', encoding='utf-8') as f:
              content = f.read()
          
          # Configure markdown with extensions for better formatting
          md = markdown.Markdown(extensions=['codehilite', 'tables', 'toc', 'fenced_code'])
          html_content = md.convert(content)
          
          print(html_content)
          " >> "$html_file"
                  
                  echo '</div></body></html>' >> "$html_file"
              fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4